//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace TaxCalculator.Data.Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class TaxCalculatorModelContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new TaxCalculatorModelContainer object using the connection string found in the 'TaxCalculatorModelContainer' section of the application configuration file.
        /// </summary>
        public TaxCalculatorModelContainer() : base("name=TaxCalculatorModelContainer", "TaxCalculatorModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TaxCalculatorModelContainer object.
        /// </summary>
        public TaxCalculatorModelContainer(string connectionString) : base(connectionString, "TaxCalculatorModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TaxCalculatorModelContainer object.
        /// </summary>
        public TaxCalculatorModelContainer(EntityConnection connection) : base(connection, "TaxCalculatorModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Company> Companies
        {
            get
            {
                if ((_Companies == null))
                {
                    _Companies = base.CreateObjectSet<Company>("Companies");
                }
                return _Companies;
            }
        }
        private ObjectSet<Company> _Companies;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Companies EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCompanies(Company company)
        {
            base.AddObject("Companies", company);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TaxCalculatorModel", Name="Company")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Company : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Company object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nume">Initial value of the Nume property.</param>
        /// <param name="adresa">Initial value of the Adresa property.</param>
        /// <param name="cUI">Initial value of the CUI property.</param>
        public static Company CreateCompany(global::System.Int64 id, global::System.String nume, global::System.String adresa, global::System.String cUI)
        {
            Company company = new Company();
            company.Id = id;
            company.Nume = nume;
            company.Adresa = adresa;
            company.CUI = cUI;
            return company;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nume
        {
            get
            {
                return _Nume;
            }
            set
            {
                OnNumeChanging(value);
                ReportPropertyChanging("Nume");
                _Nume = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nume");
                OnNumeChanged();
            }
        }
        private global::System.String _Nume;
        partial void OnNumeChanging(global::System.String value);
        partial void OnNumeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Adresa
        {
            get
            {
                return _Adresa;
            }
            set
            {
                OnAdresaChanging(value);
                ReportPropertyChanging("Adresa");
                _Adresa = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Adresa");
                OnAdresaChanged();
            }
        }
        private global::System.String _Adresa;
        partial void OnAdresaChanging(global::System.String value);
        partial void OnAdresaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CUI
        {
            get
            {
                return _CUI;
            }
            set
            {
                OnCUIChanging(value);
                ReportPropertyChanging("CUI");
                _CUI = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CUI");
                OnCUIChanged();
            }
        }
        private global::System.String _CUI;
        partial void OnCUIChanging(global::System.String value);
        partial void OnCUIChanged();

        #endregion

    
    }

    #endregion

    
}
