//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CashBook.Data.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CashBookEntities : DbContext
    {
        public CashBookEntities()
            : base("name=CashBookEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<RegistruCasaIntrare> RegistruCasaIntrares { get; set; }
        public DbSet<RegistruCasa> RegistruCasas { get; set; }
        public DbSet<Societate> Societates { get; set; }
        public DbSet<Setari> Setaris { get; set; }
        public DbSet<RegistruCasaZi> RegistruCasaZis { get; set; }
    }
}
