//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CashBook.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistruCasaIntrare
    {
        public int Id { get; set; }
        public int NrCrt { get; set; }
        public string NrActCasa { get; set; }
        public int NrAnexe { get; set; }
        public string Explicatii { get; set; }
        public decimal Incasari { get; set; }
        public decimal Plati { get; set; }
        public int RegistruCasaZiId { get; set; }
    }
}
