//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("CashBook", "SocietateRegistruCasa", "Societate", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CashBook.Data.Model.Societate), "RegistruCasa", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CashBook.Data.Model.RegistruCasa), true)]
[assembly: EdmRelationshipAttribute("CashBook", "RegistruCasaZiRegistruCasaIntrare", "RegistruCasaZi", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CashBook.Data.Model.RegistruCasaZi), "RegistruCasaIntrare", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CashBook.Data.Model.RegistruCasaIntrare), true)]
[assembly: EdmRelationshipAttribute("CashBook", "RegistruCasaRegistruCasaZi", "RegistruCasa", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CashBook.Data.Model.RegistruCasa), "RegistruCasaZi", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CashBook.Data.Model.RegistruCasaZi), true)]

#endregion

namespace CashBook.Data.Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CashBookContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new CashBookContainer object using the connection string found in the 'CashBookContainer' section of the application configuration file.
        /// </summary>
        public CashBookContainer() : base("name=CashBookContainer", "CashBookContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CashBookContainer object.
        /// </summary>
        public CashBookContainer(string connectionString) : base(connectionString, "CashBookContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CashBookContainer object.
        /// </summary>
        public CashBookContainer(EntityConnection connection) : base(connection, "CashBookContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Settings> Settings
        {
            get
            {
                if ((_Settings == null))
                {
                    _Settings = base.CreateObjectSet<Settings>("Settings");
                }
                return _Settings;
            }
        }
        private ObjectSet<Settings> _Settings;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<RegistruCasa> RegistruCasas
        {
            get
            {
                if ((_RegistruCasas == null))
                {
                    _RegistruCasas = base.CreateObjectSet<RegistruCasa>("RegistruCasas");
                }
                return _RegistruCasas;
            }
        }
        private ObjectSet<RegistruCasa> _RegistruCasas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Societate> Societates
        {
            get
            {
                if ((_Societates == null))
                {
                    _Societates = base.CreateObjectSet<Societate>("Societates");
                }
                return _Societates;
            }
        }
        private ObjectSet<Societate> _Societates;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<RegistruCasaIntrare> RegistruCasaIntrares
        {
            get
            {
                if ((_RegistruCasaIntrares == null))
                {
                    _RegistruCasaIntrares = base.CreateObjectSet<RegistruCasaIntrare>("RegistruCasaIntrares");
                }
                return _RegistruCasaIntrares;
            }
        }
        private ObjectSet<RegistruCasaIntrare> _RegistruCasaIntrares;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<RegistruCasaZi> RegistruCasaZis
        {
            get
            {
                if ((_RegistruCasaZis == null))
                {
                    _RegistruCasaZis = base.CreateObjectSet<RegistruCasaZi>("RegistruCasaZis");
                }
                return _RegistruCasaZis;
            }
        }
        private ObjectSet<RegistruCasaZi> _RegistruCasaZis;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Settings EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSettings(Settings settings)
        {
            base.AddObject("Settings", settings);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the RegistruCasas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRegistruCasas(RegistruCasa registruCasa)
        {
            base.AddObject("RegistruCasas", registruCasa);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Societates EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSocietates(Societate societate)
        {
            base.AddObject("Societates", societate);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the RegistruCasaIntrares EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRegistruCasaIntrares(RegistruCasaIntrare registruCasaIntrare)
        {
            base.AddObject("RegistruCasaIntrares", registruCasaIntrare);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the RegistruCasaZis EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRegistruCasaZis(RegistruCasaZi registruCasaZi)
        {
            base.AddObject("RegistruCasaZis", registruCasaZi);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CashBook", Name="RegistruCasa")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RegistruCasa : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new RegistruCasa object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="societateId">Initial value of the SocietateId property.</param>
        /// <param name="coinType">Initial value of the CoinType property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="coinDecimals">Initial value of the CoinDecimals property.</param>
        /// <param name="initialBalance">Initial value of the InitialBalance property.</param>
        /// <param name="location">Initial value of the Location property.</param>
        /// <param name="account">Initial value of the Account property.</param>
        /// <param name="cashierName">Initial value of the CashierName property.</param>
        public static RegistruCasa CreateRegistruCasa(global::System.Int64 id, global::System.Int64 societateId, global::System.String coinType, global::System.String name, global::System.Byte coinDecimals, global::System.Decimal initialBalance, global::System.String location, global::System.String account, global::System.String cashierName)
        {
            RegistruCasa registruCasa = new RegistruCasa();
            registruCasa.Id = id;
            registruCasa.SocietateId = societateId;
            registruCasa.CoinType = coinType;
            registruCasa.Name = name;
            registruCasa.CoinDecimals = coinDecimals;
            registruCasa.InitialBalance = initialBalance;
            registruCasa.Location = location;
            registruCasa.Account = account;
            registruCasa.CashierName = cashierName;
            return registruCasa;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 SocietateId
        {
            get
            {
                return _SocietateId;
            }
            set
            {
                OnSocietateIdChanging(value);
                ReportPropertyChanging("SocietateId");
                _SocietateId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SocietateId");
                OnSocietateIdChanged();
            }
        }
        private global::System.Int64 _SocietateId;
        partial void OnSocietateIdChanging(global::System.Int64 value);
        partial void OnSocietateIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CoinType
        {
            get
            {
                return _CoinType;
            }
            set
            {
                OnCoinTypeChanging(value);
                ReportPropertyChanging("CoinType");
                _CoinType = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CoinType");
                OnCoinTypeChanged();
            }
        }
        private global::System.String _CoinType;
        partial void OnCoinTypeChanging(global::System.String value);
        partial void OnCoinTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte CoinDecimals
        {
            get
            {
                return _CoinDecimals;
            }
            set
            {
                OnCoinDecimalsChanging(value);
                ReportPropertyChanging("CoinDecimals");
                _CoinDecimals = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CoinDecimals");
                OnCoinDecimalsChanged();
            }
        }
        private global::System.Byte _CoinDecimals;
        partial void OnCoinDecimalsChanging(global::System.Byte value);
        partial void OnCoinDecimalsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal InitialBalance
        {
            get
            {
                return _InitialBalance;
            }
            set
            {
                OnInitialBalanceChanging(value);
                ReportPropertyChanging("InitialBalance");
                _InitialBalance = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("InitialBalance");
                OnInitialBalanceChanged();
            }
        }
        private global::System.Decimal _InitialBalance;
        partial void OnInitialBalanceChanging(global::System.Decimal value);
        partial void OnInitialBalanceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Location
        {
            get
            {
                return _Location;
            }
            set
            {
                OnLocationChanging(value);
                ReportPropertyChanging("Location");
                _Location = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Location");
                OnLocationChanged();
            }
        }
        private global::System.String _Location;
        partial void OnLocationChanging(global::System.String value);
        partial void OnLocationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Account
        {
            get
            {
                return _Account;
            }
            set
            {
                OnAccountChanging(value);
                ReportPropertyChanging("Account");
                _Account = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Account");
                OnAccountChanged();
            }
        }
        private global::System.String _Account;
        partial void OnAccountChanging(global::System.String value);
        partial void OnAccountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CashierName
        {
            get
            {
                return _CashierName;
            }
            set
            {
                OnCashierNameChanging(value);
                ReportPropertyChanging("CashierName");
                _CashierName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CashierName");
                OnCashierNameChanged();
            }
        }
        private global::System.String _CashierName;
        partial void OnCashierNameChanging(global::System.String value);
        partial void OnCashierNameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CashBook", "SocietateRegistruCasa", "Societate")]
        public Societate Societate
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Societate>("CashBook.SocietateRegistruCasa", "Societate").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Societate>("CashBook.SocietateRegistruCasa", "Societate").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Societate> SocietateReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Societate>("CashBook.SocietateRegistruCasa", "Societate");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Societate>("CashBook.SocietateRegistruCasa", "Societate", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CashBook", "RegistruCasaRegistruCasaZi", "RegistruCasaZi")]
        public EntityCollection<RegistruCasaZi> RegistruCasaZis
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RegistruCasaZi>("CashBook.RegistruCasaRegistruCasaZi", "RegistruCasaZi");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RegistruCasaZi>("CashBook.RegistruCasaRegistruCasaZi", "RegistruCasaZi", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CashBook", Name="RegistruCasaIntrare")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RegistruCasaIntrare : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new RegistruCasaIntrare object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nrCrt">Initial value of the NrCrt property.</param>
        /// <param name="nrActCasa">Initial value of the NrActCasa property.</param>
        /// <param name="nrAnexe">Initial value of the NrAnexe property.</param>
        /// <param name="explicatii">Initial value of the Explicatii property.</param>
        /// <param name="incasari">Initial value of the Incasari property.</param>
        /// <param name="plati">Initial value of the Plati property.</param>
        /// <param name="registruCasaZiId">Initial value of the RegistruCasaZiId property.</param>
        public static RegistruCasaIntrare CreateRegistruCasaIntrare(global::System.Int64 id, global::System.Int32 nrCrt, global::System.String nrActCasa, global::System.Int32 nrAnexe, global::System.String explicatii, global::System.Decimal incasari, global::System.Decimal plati, global::System.Int64 registruCasaZiId)
        {
            RegistruCasaIntrare registruCasaIntrare = new RegistruCasaIntrare();
            registruCasaIntrare.Id = id;
            registruCasaIntrare.NrCrt = nrCrt;
            registruCasaIntrare.NrActCasa = nrActCasa;
            registruCasaIntrare.NrAnexe = nrAnexe;
            registruCasaIntrare.Explicatii = explicatii;
            registruCasaIntrare.Incasari = incasari;
            registruCasaIntrare.Plati = plati;
            registruCasaIntrare.RegistruCasaZiId = registruCasaZiId;
            return registruCasaIntrare;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 NrCrt
        {
            get
            {
                return _NrCrt;
            }
            set
            {
                OnNrCrtChanging(value);
                ReportPropertyChanging("NrCrt");
                _NrCrt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NrCrt");
                OnNrCrtChanged();
            }
        }
        private global::System.Int32 _NrCrt;
        partial void OnNrCrtChanging(global::System.Int32 value);
        partial void OnNrCrtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NrActCasa
        {
            get
            {
                return _NrActCasa;
            }
            set
            {
                OnNrActCasaChanging(value);
                ReportPropertyChanging("NrActCasa");
                _NrActCasa = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NrActCasa");
                OnNrActCasaChanged();
            }
        }
        private global::System.String _NrActCasa;
        partial void OnNrActCasaChanging(global::System.String value);
        partial void OnNrActCasaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 NrAnexe
        {
            get
            {
                return _NrAnexe;
            }
            set
            {
                OnNrAnexeChanging(value);
                ReportPropertyChanging("NrAnexe");
                _NrAnexe = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NrAnexe");
                OnNrAnexeChanged();
            }
        }
        private global::System.Int32 _NrAnexe;
        partial void OnNrAnexeChanging(global::System.Int32 value);
        partial void OnNrAnexeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Explicatii
        {
            get
            {
                return _Explicatii;
            }
            set
            {
                OnExplicatiiChanging(value);
                ReportPropertyChanging("Explicatii");
                _Explicatii = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Explicatii");
                OnExplicatiiChanged();
            }
        }
        private global::System.String _Explicatii;
        partial void OnExplicatiiChanging(global::System.String value);
        partial void OnExplicatiiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Incasari
        {
            get
            {
                return _Incasari;
            }
            set
            {
                OnIncasariChanging(value);
                ReportPropertyChanging("Incasari");
                _Incasari = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Incasari");
                OnIncasariChanged();
            }
        }
        private global::System.Decimal _Incasari;
        partial void OnIncasariChanging(global::System.Decimal value);
        partial void OnIncasariChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Plati
        {
            get
            {
                return _Plati;
            }
            set
            {
                OnPlatiChanging(value);
                ReportPropertyChanging("Plati");
                _Plati = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Plati");
                OnPlatiChanged();
            }
        }
        private global::System.Decimal _Plati;
        partial void OnPlatiChanging(global::System.Decimal value);
        partial void OnPlatiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 RegistruCasaZiId
        {
            get
            {
                return _RegistruCasaZiId;
            }
            set
            {
                OnRegistruCasaZiIdChanging(value);
                ReportPropertyChanging("RegistruCasaZiId");
                _RegistruCasaZiId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RegistruCasaZiId");
                OnRegistruCasaZiIdChanged();
            }
        }
        private global::System.Int64 _RegistruCasaZiId;
        partial void OnRegistruCasaZiIdChanging(global::System.Int64 value);
        partial void OnRegistruCasaZiIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CashBook", "RegistruCasaZiRegistruCasaIntrare", "RegistruCasaZi")]
        public RegistruCasaZi RegistruCasaZi
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RegistruCasaZi>("CashBook.RegistruCasaZiRegistruCasaIntrare", "RegistruCasaZi").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RegistruCasaZi>("CashBook.RegistruCasaZiRegistruCasaIntrare", "RegistruCasaZi").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<RegistruCasaZi> RegistruCasaZiReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RegistruCasaZi>("CashBook.RegistruCasaZiRegistruCasaIntrare", "RegistruCasaZi");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<RegistruCasaZi>("CashBook.RegistruCasaZiRegistruCasaIntrare", "RegistruCasaZi", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CashBook", Name="RegistruCasaZi")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RegistruCasaZi : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new RegistruCasaZi object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="data">Initial value of the Data property.</param>
        /// <param name="registruCasaId">Initial value of the RegistruCasaId property.</param>
        public static RegistruCasaZi CreateRegistruCasaZi(global::System.Int64 id, global::System.DateTime data, global::System.Int64 registruCasaId)
        {
            RegistruCasaZi registruCasaZi = new RegistruCasaZi();
            registruCasaZi.Id = id;
            registruCasaZi.Data = data;
            registruCasaZi.RegistruCasaId = registruCasaId;
            return registruCasaZi;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Data
        {
            get
            {
                return _Data;
            }
            set
            {
                OnDataChanging(value);
                ReportPropertyChanging("Data");
                _Data = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Data");
                OnDataChanged();
            }
        }
        private global::System.DateTime _Data;
        partial void OnDataChanging(global::System.DateTime value);
        partial void OnDataChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 RegistruCasaId
        {
            get
            {
                return _RegistruCasaId;
            }
            set
            {
                OnRegistruCasaIdChanging(value);
                ReportPropertyChanging("RegistruCasaId");
                _RegistruCasaId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RegistruCasaId");
                OnRegistruCasaIdChanged();
            }
        }
        private global::System.Int64 _RegistruCasaId;
        partial void OnRegistruCasaIdChanging(global::System.Int64 value);
        partial void OnRegistruCasaIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CashBook", "RegistruCasaZiRegistruCasaIntrare", "RegistruCasaIntrare")]
        public EntityCollection<RegistruCasaIntrare> RegistruCasaIntrares
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RegistruCasaIntrare>("CashBook.RegistruCasaZiRegistruCasaIntrare", "RegistruCasaIntrare");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RegistruCasaIntrare>("CashBook.RegistruCasaZiRegistruCasaIntrare", "RegistruCasaIntrare", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CashBook", "RegistruCasaRegistruCasaZi", "RegistruCasa")]
        public RegistruCasa RegistruCasa
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RegistruCasa>("CashBook.RegistruCasaRegistruCasaZi", "RegistruCasa").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RegistruCasa>("CashBook.RegistruCasaRegistruCasaZi", "RegistruCasa").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<RegistruCasa> RegistruCasaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RegistruCasa>("CashBook.RegistruCasaRegistruCasaZi", "RegistruCasa");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<RegistruCasa>("CashBook.RegistruCasaRegistruCasaZi", "RegistruCasa", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CashBook", Name="Settings")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Settings : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Settings object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="key">Initial value of the Key property.</param>
        /// <param name="value">Initial value of the Value property.</param>
        public static Settings CreateSettings(global::System.Int64 id, global::System.String key, global::System.String value)
        {
            Settings settings = new Settings();
            settings.Id = id;
            settings.Key = key;
            settings.Value = value;
            return settings;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Key
        {
            get
            {
                return _Key;
            }
            set
            {
                OnKeyChanging(value);
                ReportPropertyChanging("Key");
                _Key = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Key");
                OnKeyChanged();
            }
        }
        private global::System.String _Key;
        partial void OnKeyChanging(global::System.String value);
        partial void OnKeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Value
        {
            get
            {
                return _Value;
            }
            set
            {
                OnValueChanging(value);
                ReportPropertyChanging("Value");
                _Value = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Value");
                OnValueChanged();
            }
        }
        private global::System.String _Value;
        partial void OnValueChanging(global::System.String value);
        partial void OnValueChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CashBook", Name="Societate")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Societate : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Societate object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nume">Initial value of the Nume property.</param>
        /// <param name="adresa">Initial value of the Adresa property.</param>
        /// <param name="cUI">Initial value of the CUI property.</param>
        public static Societate CreateSocietate(global::System.Int64 id, global::System.String nume, global::System.String adresa, global::System.String cUI)
        {
            Societate societate = new Societate();
            societate.Id = id;
            societate.Nume = nume;
            societate.Adresa = adresa;
            societate.CUI = cUI;
            return societate;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nume
        {
            get
            {
                return _Nume;
            }
            set
            {
                OnNumeChanging(value);
                ReportPropertyChanging("Nume");
                _Nume = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nume");
                OnNumeChanged();
            }
        }
        private global::System.String _Nume;
        partial void OnNumeChanging(global::System.String value);
        partial void OnNumeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Adresa
        {
            get
            {
                return _Adresa;
            }
            set
            {
                OnAdresaChanging(value);
                ReportPropertyChanging("Adresa");
                _Adresa = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Adresa");
                OnAdresaChanged();
            }
        }
        private global::System.String _Adresa;
        partial void OnAdresaChanging(global::System.String value);
        partial void OnAdresaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CUI
        {
            get
            {
                return _CUI;
            }
            set
            {
                OnCUIChanging(value);
                ReportPropertyChanging("CUI");
                _CUI = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CUI");
                OnCUIChanged();
            }
        }
        private global::System.String _CUI;
        partial void OnCUIChanging(global::System.String value);
        partial void OnCUIChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CashBook", "SocietateRegistruCasa", "RegistruCasa")]
        public EntityCollection<RegistruCasa> RegistreCasa
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RegistruCasa>("CashBook.SocietateRegistruCasa", "RegistruCasa");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RegistruCasa>("CashBook.SocietateRegistruCasa", "RegistruCasa", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
