//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("TaxCalculatorModel", "TaxCalculationsIndicator", "TaxCalculations", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TaxCalculator.Data.Model.TaxCalculations), "Indicator", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TaxCalculator.Data.Model.Indicator), true)]
[assembly: EdmRelationshipAttribute("TaxCalculatorModel", "TaxCalculationsCompany", "TaxCalculations", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TaxCalculator.Data.Model.TaxCalculations), "Company", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TaxCalculator.Data.Model.Company), true)]

#endregion

namespace TaxCalculator.Data.Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class TaxCalculatorModelContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new TaxCalculatorModelContainer object using the connection string found in the 'TaxCalculatorModelContainer' section of the application configuration file.
        /// </summary>
        public TaxCalculatorModelContainer() : base("name=TaxCalculatorModelContainer", "TaxCalculatorModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TaxCalculatorModelContainer object.
        /// </summary>
        public TaxCalculatorModelContainer(string connectionString) : base(connectionString, "TaxCalculatorModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TaxCalculatorModelContainer object.
        /// </summary>
        public TaxCalculatorModelContainer(EntityConnection connection) : base(connection, "TaxCalculatorModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Company> Companies
        {
            get
            {
                if ((_Companies == null))
                {
                    _Companies = base.CreateObjectSet<Company>("Companies");
                }
                return _Companies;
            }
        }
        private ObjectSet<Company> _Companies;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Indicator> Indicators
        {
            get
            {
                if ((_Indicators == null))
                {
                    _Indicators = base.CreateObjectSet<Indicator>("Indicators");
                }
                return _Indicators;
            }
        }
        private ObjectSet<Indicator> _Indicators;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Settings> Settings
        {
            get
            {
                if ((_Settings == null))
                {
                    _Settings = base.CreateObjectSet<Settings>("Settings");
                }
                return _Settings;
            }
        }
        private ObjectSet<Settings> _Settings;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TaxCalculations> TaxCalculations
        {
            get
            {
                if ((_TaxCalculations == null))
                {
                    _TaxCalculations = base.CreateObjectSet<TaxCalculations>("TaxCalculations");
                }
                return _TaxCalculations;
            }
        }
        private ObjectSet<TaxCalculations> _TaxCalculations;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Companies EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCompanies(Company company)
        {
            base.AddObject("Companies", company);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Indicators EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToIndicators(Indicator indicator)
        {
            base.AddObject("Indicators", indicator);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Settings EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSettings(Settings settings)
        {
            base.AddObject("Settings", settings);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TaxCalculations EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTaxCalculations(TaxCalculations taxCalculations)
        {
            base.AddObject("TaxCalculations", taxCalculations);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TaxCalculatorModel", Name="Company")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Company : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Company object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="address">Initial value of the Address property.</param>
        /// <param name="cUI">Initial value of the CUI property.</param>
        public static Company CreateCompany(global::System.Int64 id, global::System.String name, global::System.String address, global::System.String cUI)
        {
            Company company = new Company();
            company.Id = id;
            company.Name = name;
            company.Address = address;
            company.CUI = cUI;
            return company;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CUI
        {
            get
            {
                return _CUI;
            }
            set
            {
                OnCUIChanging(value);
                ReportPropertyChanging("CUI");
                _CUI = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CUI");
                OnCUIChanged();
            }
        }
        private global::System.String _CUI;
        partial void OnCUIChanging(global::System.String value);
        partial void OnCUIChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TaxCalculatorModel", Name="Indicator")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Indicator : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Indicator object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="createdTimestamp">Initial value of the CreatedTimestamp property.</param>
        /// <param name="isDefault">Initial value of the IsDefault property.</param>
        public static Indicator CreateIndicator(global::System.Int64 id, global::System.String name, global::System.DateTime createdTimestamp, global::System.Boolean isDefault)
        {
            Indicator indicator = new Indicator();
            indicator.Id = id;
            indicator.Name = name;
            indicator.CreatedTimestamp = createdTimestamp;
            indicator.IsDefault = isDefault;
            return indicator;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Content
        {
            get
            {
                return _Content;
            }
            set
            {
                OnContentChanging(value);
                ReportPropertyChanging("Content");
                _Content = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Content");
                OnContentChanged();
            }
        }
        private global::System.String _Content;
        partial void OnContentChanging(global::System.String value);
        partial void OnContentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreatedTimestamp
        {
            get
            {
                return _CreatedTimestamp;
            }
            set
            {
                OnCreatedTimestampChanging(value);
                ReportPropertyChanging("CreatedTimestamp");
                _CreatedTimestamp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedTimestamp");
                OnCreatedTimestampChanged();
            }
        }
        private global::System.DateTime _CreatedTimestamp;
        partial void OnCreatedTimestampChanging(global::System.DateTime value);
        partial void OnCreatedTimestampChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsDefault
        {
            get
            {
                return _IsDefault;
            }
            set
            {
                OnIsDefaultChanging(value);
                ReportPropertyChanging("IsDefault");
                _IsDefault = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsDefault");
                OnIsDefaultChanged();
            }
        }
        private global::System.Boolean _IsDefault;
        partial void OnIsDefaultChanging(global::System.Boolean value);
        partial void OnIsDefaultChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TaxCalculatorModel", Name="Settings")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Settings : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Settings object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="key">Initial value of the Key property.</param>
        /// <param name="value">Initial value of the Value property.</param>
        public static Settings CreateSettings(global::System.Int64 id, global::System.String key, global::System.String value)
        {
            Settings settings = new Settings();
            settings.Id = id;
            settings.Key = key;
            settings.Value = value;
            return settings;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Key
        {
            get
            {
                return _Key;
            }
            set
            {
                OnKeyChanging(value);
                ReportPropertyChanging("Key");
                _Key = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Key");
                OnKeyChanged();
            }
        }
        private global::System.String _Key;
        partial void OnKeyChanging(global::System.String value);
        partial void OnKeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Value
        {
            get
            {
                return _Value;
            }
            set
            {
                OnValueChanging(value);
                ReportPropertyChanging("Value");
                _Value = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Value");
                OnValueChanged();
            }
        }
        private global::System.String _Value;
        partial void OnValueChanging(global::System.String value);
        partial void OnValueChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TaxCalculatorModel", Name="TaxCalculations")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TaxCalculations : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TaxCalculations object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="indicatorId">Initial value of the IndicatorId property.</param>
        /// <param name="rectifying">Initial value of the Rectifying property.</param>
        /// <param name="companyId">Initial value of the CompanyId property.</param>
        public static TaxCalculations CreateTaxCalculations(global::System.Int64 id, global::System.Int64 indicatorId, global::System.Boolean rectifying, global::System.Int64 companyId)
        {
            TaxCalculations taxCalculations = new TaxCalculations();
            taxCalculations.Id = id;
            taxCalculations.IndicatorId = indicatorId;
            taxCalculations.Rectifying = rectifying;
            taxCalculations.CompanyId = companyId;
            return taxCalculations;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Content
        {
            get
            {
                return _Content;
            }
            set
            {
                OnContentChanging(value);
                ReportPropertyChanging("Content");
                _Content = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Content");
                OnContentChanged();
            }
        }
        private global::System.String _Content;
        partial void OnContentChanging(global::System.String value);
        partial void OnContentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 IndicatorId
        {
            get
            {
                return _IndicatorId;
            }
            set
            {
                OnIndicatorIdChanging(value);
                ReportPropertyChanging("IndicatorId");
                _IndicatorId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IndicatorId");
                OnIndicatorIdChanged();
            }
        }
        private global::System.Int64 _IndicatorId;
        partial void OnIndicatorIdChanging(global::System.Int64 value);
        partial void OnIndicatorIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Rectifying
        {
            get
            {
                return _Rectifying;
            }
            set
            {
                OnRectifyingChanging(value);
                ReportPropertyChanging("Rectifying");
                _Rectifying = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Rectifying");
                OnRectifyingChanged();
            }
        }
        private global::System.Boolean _Rectifying;
        partial void OnRectifyingChanging(global::System.Boolean value);
        partial void OnRectifyingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 CompanyId
        {
            get
            {
                return _CompanyId;
            }
            set
            {
                OnCompanyIdChanging(value);
                ReportPropertyChanging("CompanyId");
                _CompanyId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CompanyId");
                OnCompanyIdChanged();
            }
        }
        private global::System.Int64 _CompanyId;
        partial void OnCompanyIdChanging(global::System.Int64 value);
        partial void OnCompanyIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OtherData
        {
            get
            {
                return _OtherData;
            }
            set
            {
                OnOtherDataChanging(value);
                ReportPropertyChanging("OtherData");
                _OtherData = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OtherData");
                OnOtherDataChanged();
            }
        }
        private global::System.String _OtherData;
        partial void OnOtherDataChanging(global::System.String value);
        partial void OnOtherDataChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TaxCalculatorModel", "TaxCalculationsIndicator", "Indicator")]
        public Indicator Indicator
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Indicator>("TaxCalculatorModel.TaxCalculationsIndicator", "Indicator").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Indicator>("TaxCalculatorModel.TaxCalculationsIndicator", "Indicator").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Indicator> IndicatorReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Indicator>("TaxCalculatorModel.TaxCalculationsIndicator", "Indicator");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Indicator>("TaxCalculatorModel.TaxCalculationsIndicator", "Indicator", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TaxCalculatorModel", "TaxCalculationsCompany", "Company")]
        public Company Company
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Company>("TaxCalculatorModel.TaxCalculationsCompany", "Company").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Company>("TaxCalculatorModel.TaxCalculationsCompany", "Company").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Company> CompanyReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Company>("TaxCalculatorModel.TaxCalculationsCompany", "Company");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Company>("TaxCalculatorModel.TaxCalculationsCompany", "Company", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
