//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CashBook.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistruCasaZi
    {
        public RegistruCasaZi()
        {
            this.RegistruCasaIntrares = new HashSet<RegistruCasaIntrare>();
        }
    
        public int Id { get; set; }
        public int RegistruCasaId { get; set; }
        public System.DateTime Data { get; set; }
    
        public virtual ICollection<RegistruCasaIntrare> RegistruCasaIntrares { get; set; }
    }
}
