//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CashBook.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistruCasa
    {
        public RegistruCasa()
        {
            this.RegistruCasaZis = new HashSet<RegistruCasaZi>();
        }
    
        public int Id { get; set; }
        public int SocietateId { get; set; }
    
        public virtual ICollection<RegistruCasaZi> RegistruCasaZis { get; set; }
    }
}
